# Site settings
title: CI and CD with GitHub
description: A demo blog
email: rickmcken@@gmail.com
github_username:  githubtraining
baseurl:
url: https://githubtraining-cicd-demo.herokuapp.com
destination: site_content
exclude: [ 'vendor' ]

markdown: kramdown
